### ISSUE TITLE
@JsonApiDatastoreConfig missing from npm package

### ISSUE THREAD

**Issue by acramatte** [ghidoz/angular2-jsonapi#1]
I've recently pulled your package from npm as a dependency of another project but it seems that the JsonApiDatastoreConfig decorator js and type definition files are missing.  

It works if I npm link the cloned repo so could it be that the files didn't make it in the last npm publish ?

Thanks for the project by the way 👍

**Comment by ghidoz** [comment]
Ehy, there! Thanks for taking the time to try my package.
I have just updated the npm package to v1.0.0, so now you'll be able to install it.

Feel free to open any issue, if you find any problem. Thanks
