### ISSUE TITLE
Renaming of library

### ISSUE THREAD

**Issue by HennerM** [ghidoz/angular2-jsonapi#101]
Hey fellow developers!

As everyone knows, the name of the library is not suited anymore, because Angular is in version 4 now. 
To make the name more clear, I want to change the name to a "version-independent" name. 
Does anyone have a strong opinion on this and good suggestions for the perfect name?

@safo6m suggestion was *ngx-json-api-store*, what do you think about this?

**Comment by jamesdixon** [comment]
How about just `ngx-jsonapi`? Clear and concise.

On a side note, great work by everyone on this library!

**Comment by jamesdixon** [comment]
One other thing to ponder:

Does the library _really_ need to be renamed? It seems like most Angular developers realize that Angular 2 libraries work with newer versions. That said, might be more of a hassle than it's worth. 

Food for thought 👍

**Comment by safo6m** [comment]
There is a peer dependency for Angular 4, so the current lib name is misleading. 
Also, Angular team suggests not to put framework version into the name.

**Comment by ghidoz** [comment]
For me, +1 for @jamesdixon suggestion. I like ngx-jsonapi :)
But what happens for developers looking for upgrades for the current library? Will they find new versions if we change the name?

**Comment by safo6m** [comment]
You can deprecated the old version on npm and a warning will be displayed if someone installs that deprecated version (I think you can specify a warning message).
