### ISSUE TITLE
updating Relationships on model save causes error 

### ISSUE THREAD

**Issue by upMKuhn** [ghidoz/angular2-jsonapi#102]
My JSON API server does not return any relationships, when I update my models. This API assumes it receives a relationshipModel· Therefore it calls the push method on an undefined variable.

Calling function: json-api-datastore.service ::  SaveRecord()
Error location json-api-datastore.service :: updateRelationships()

Error message undefined.push()  
         relationshipModel[propertyHasMany.propertyName].push(model);

Thanks For helping and the api :)

**Comment by HennerM** [comment]
This gets fixed in #93
