### ISSUE TITLE
Should createOrPeek update local data if record already exists? 

### ISSUE THREAD

**Issue by chaumo** [ghidoz/angular2-jsonapi#105]
I'm facing an issue when receiving and parsing a server response with updated data on some of the relationship models. 
Not sure if there's some error on the library or if I'm missing something, so sorry if that's the case. 

When doing a find or save with include params I get the whole response from backend (current entity and related models).
* If some of those related models (received on the response) are not yet on the local datastore they are created on the fly (createOrPeek) and available for futher use -> thats OK
* But if some of those records already exists on local datastore, the createOrPeek returns current datastore object, ignoring response data (which may be newer updated data that 'should' be updated also on local datastore)

A simple example where this could be useful: 
Send a request to create a 'vote' which belongs to a 'entity', the server replies with a vote object and its current relathionship for the 'entity' class, which may have a 'total votes' field (or similar).  

Could the createOrPeek have something like this to merge received data with local datastore? 
```
if (peek) {
  _.extend(peek, data.attributes);
  return peek;
}
```

**Comment by HennerM** [comment]
I agree, in this case it probably would make sense. 
Do you want so implement this change or should I do it?

**Comment by chaumo** [comment]
Would be great if you could add it. I'm still quite new to angular and not sure if that change (even if it seems quite simple) could break anything else.

BTW, thanks for your effort and keep with the good work ;)
