### ISSUE TITLE
Getting error on [204] No Content Response

### ISSUE THREAD

**Issue by ricardo-neves-kununu** [ghidoz/angular2-jsonapi#106]
`TypeError: Cannot read property 'data' of null`
`at DatastoreService.webpackJsonp.../../../../angular2-jsonapi/dist/services/json-api-datastore.service.js.JsonApiDatastore.extractRecordData (json-api-datastore.service.js:188)`

**Comment by RicardoNeves** [comment]
I've made a fix with PR #107

**Comment by HennerM** [comment]
I modified your solution a bit and published it to npm. I added a check that the response only gets parsed if the response HTTP status is 201, this could be a breaking change if someone relies on server with broken specification.
