### ISSUE TITLE
How do you handle retries?

### ISSUE THREAD

**Issue by moneal** [ghidoz/angular2-jsonapi#114]
The handleError method does not receive all the request information so I can't see how to implement a retry function. I would like to catch 401 responses and renew my JWT and try the request over again.

I think my issue is also related to the CORS OPTIONS requests returning a 401 response. This is what is causing the status to return as 0.

**Comment by ricardo-neves-kununu** [comment]
Not sure exactly what else is missing in your case to refresh your JWT, but maybe this can help.
For me, I've created a DatastoreWrapperService that encapsulates the datastoreService... 
Then I handle 401 responses by refreshing the token and making the request again.

datastore-wrapper.service.ts:
`return this.datastoreService.saveRecord(attributesMetadata, model, params, this.getAuthenticationHeaders(account))
      .catch((error: Response) => {
        if (error.status !== 401) {
          return Observable.throw(error);
        }

        return this.authenticationService.refreshAccessToken()
          .flatMap((newAccount) => {
            return this.datastoreService.saveRecord(attributesMetadata, model, params, this.getAuthenticationHeaders(newAccount));
          });
      });`

datastore.service.ts
`handleError(error: any): ErrorObservable {
    return Observable.throw(error);
  }`

**Comment by edgarmartins** [comment]
Hi, Can you write the complete soluction? Thanks!

**Comment by ricardo-neves-kununu** [comment]
Sorry for the late response. It's a simple http request to an endpoint like /refresh where I pass the refreshToken for that user and I get a new accessToken. Then I update the access token value for this user, so that it can be used for future requests.

**Comment by ricardo-neves-kununu** [comment]
@HennerM can we close this?
