### ISSUE TITLE
How to handle single resources?

### ISSUE THREAD

**Issue by ricardo-neves-kununu** [ghidoz/angular2-jsonapi#122]
Is there a way of handling single resources like /me ?

**Comment by hpawe01** [comment]
I think this is out of scope for this library as it "only" implements the [JSON API specification](http://jsonapi.org/format/). And this spec [says](http://jsonapi.org/format/#document-top-level), that each response **must** have the top-level member `data` and that this **must** contain either a single resource or an array of single resources. And each single resource **must** contain a `type` and an `id`.

So in my understanding you could either create a resource type `me` with only one object (id = 1) and call it with `/me/1`, or you don't use this library to handle requests/ responses that do not comply with the JSON API spec.

**Comment by HennerM** [comment]
As @hpawe01 pointed out it is indeed out of scope.
