### ISSUE TITLE
Model is not filled correctly when some of the server response attributes are FALSE

### ISSUE THREAD

**Issue by hsaldarriaga** [ghidoz/angular2-jsonapi#134]
When json api server send an attribute of type boolean with value 'false', the model attribute is not filled and stayed as undefined 

https://github.com/ghidoz/angular2-jsonapi/blob/95e6258915ab3fd6637c05a28516a99028389acb/src/services/json-api-datastore.service.ts#L421

I recommend to change the if condition with `attributes[serializedName] !== undefined`

That could happen when the attribute sent from server is a number equal 0, but I hadn't tested this case

**Comment by hsaldarriaga** [comment]
It seems is the same in #126

**Comment by HennerM** [comment]
Fixed in PR #127 in release 4.0.2
