### ISSUE TITLE
Model does not save property of type Date if value of property is null returned from api server.

### ISSUE THREAD

**Issue by voronizer** [ghidoz/angular2-jsonapi#138]
```javascript
this.datastore.findRecord(Post, '1').subscribe(
    (item) => {
          // item.myDate == undefined
          item.myDate = new Date();
          // item.hasDirtyAttributes == false
          // so, when call item.save() it sends request with empty attributes of item.
     }
);
```

**Comment by jacobbullock** [comment]
@voronizer I just tested this and it did save correctly.  your example shows only calling .save(), but the docs say that you have to append .subscribe() or the save method is never called.  

    this.datastore.findRecord(User, '1').subscribe(
        (record: User) => {
            record.birthdate = new Date();
            console.log(record.hasDirtyAttributes); //false
            record.save().subscribe(
                (record2: User) => console.log(record2) //birthdate: Jan 04 2018
            );
        }
    );

**Comment by HennerM** [comment]
Thanks @jacobbullock, thats right. Due to the lazy nature of observables, the request only gets sent when the observable gets subscribed.

**Comment by voronizer** [comment]
Issue is not in calling/not calling .subscribe().

Issue in:

record.birthdate = new Date();
->> console.log(record.hasDirtyAttributes); //false

Why record.hasDirtyAttributes is false in this case?
It should be true because of birthdate was changed.

**Comment by jacobbullock** [comment]
Your original comment said that the object wasn’t saving, but it definitely is saving. Perhaps there is another bug in *hasDirtyAttributes*, but can you confirm if adding .subscribe() does in fact save the object?

**Comment by voronizer** [comment]
Yes. Sure. Its saving e.q. sending data to server while calling _.subscribe()_.
May be there was inaccurate description of the problem. Sorry.

In fact, yes, there is the problem with _hasDirtyAttributes_.

Let's clarify original post:

```javascript
this.datastore.findRecord(Post, '1').subscribe(
    (item) => {
          // item.myDate == undefined
          item.myDate = new Date();
          // item.hasDirtyAttributes == false
          // so, when call item.save().subscribe() it sends request with empty attributes of item.
          // there is no myDate attribute in post request.
     }
);
```

**Comment by jacobbullock** [comment]
@voronizer can you print your server logs or something that is showing it is sending empty attributes?  is it possible you don't have the decorators setup right not the model?
