### ISSUE TITLE
Gem for generating angular2-jsonapi models from rails

### ISSUE THREAD

**Issue by jacobbullock** [ghidoz/angular2-jsonapi#143]
Not sure if this is the right place to put this, but we started integrating this library into our angular front end and we have a lot of models to manage.  So I wrote this gem to handle automatically generating models based on the db schema and active model serializers.  It has worked great for our uses so far, but wanted to share here in the event someone could benefit from it.   I will be updating this to work with our iOS CoreData stack as well

https://github.com/oncore-education/jsonapi_models

**Comment by HennerM** [comment]
Thanks! I am not using rails but this looks awesome ;)
I will mention it on the README.
