### ISSUE TITLE
How to remove a relationship?

### ISSUE THREAD

**Issue by ricardo-neves-kununu** [ghidoz/angular2-jsonapi#146]
I'm trying to remove an entity relationship by setting it to null, but for some reason on the PATCH request the null values doesn't get sent.
When I checked the docs I found this: http://jsonapi.org/format/#crud-updating-relationships

For what I know, this is not implemented yet. Any ideas how to achieve this with the current solution.

**Comment by clementprdhomme** [comment]
The error is located here: https://github.com/ghidoz/angular2-jsonapi/blob/master/src/services/json-api-datastore.service.ts#L197-L215
```ts
protected getRelationships(data: any): any {
    let relationships: any;

    for (const key in data) {
      if (data.hasOwnProperty(key)) {
        if (data[key] instanceof JsonApiModel) {
          relationships = relationships || {};
          
          if (data[key].id) {
            relationships[key] = {
              data: this.buildSingleRelationshipData(data[key])
            };
          }
        } else if (data[key] instanceof Array && data[key].length > 0 && this.isValidToManyRelation(data[key])) {
          relationships = relationships || {};

          const relationshipData = data[key]
            .filter((model: JsonApiModel) => model.id)
            .map((model: JsonApiModel) => this.buildSingleRelationshipData(model));

          relationships[key] = {
            data: relationshipData
          };
        }
      }
    }

    return relationships;
}
```

When a relationship has been set to `null`, in this function, `data[key]` is also `null` so the change is discarded.

**Comment by ricardo-neves-kununu** [comment]
So this means that we could only accomplish this with something like this: 
```
PATCH /articles/1/relationships/author HTTP/1.1
Content-Type: application/vnd.api+json
Accept: application/vnd.api+json

{
  "data": null
}
```
Like explained here: http://jsonapi.org/format/#crud-updating-relationships

But this is not implemented yet either. Correct?

**Comment by HennerM** [comment]
Hey!

I just took a look at this issue but I am not quite sure yet how this should be handled.
How have you defined your models? Something like this: `@BelongsTo()  author: Author | null;`. Otherwise you wouldn't be able to set it to null I guess.

**Comment by HennerM** [comment]
@ricardo-neves-kununu @clementprdhomme I created a PR: #148, it's not fully done yet, would this approach be feasible in your opinions?

**Comment by jmagalhaes-xing** [comment]
@HennerM I took a look at the PR and that seems fine. I already had a similar approach in a fork I did because I was having the same issue.

4.0.3 seems broken though, `saveRecord` is sending empty attributes

**Comment by ricardo-neves-kununu** [comment]
Sorry @HennerM I've been a little bit busy. I'll try to have a look at this week.
