### ISSUE TITLE
Migration Angular 5

### ISSUE THREAD

**Issue by Scipionh** [ghidoz/angular2-jsonapi#147]
Would it be possible to migrate Angular from 4 to 5 ?

Thanks

**Comment by HennerM** [comment]
Are there any other issues apart from the peer dependency warnings? I already use the library just fine with an Angular 5 application.

**Comment by Mojo1** [comment]
Using it as well with angular 5 - no issues so far but dependency update would be nice

**Comment by cguilhermef** [comment]
When I fill the constructor `super()` of Datastore class (that extends JsonApiDatastore), IDE hint that `Http` is deprecated. Angular 5 deprecated Http in favor of HttpClient

**Comment by hpawe01** [comment]
@cguilhermef This is already reported (#95) and there is a unfinished pull request (#96), but I don't know what the current status is.

**Comment by cguilhermef** [comment]
@hpawe01 thanks! I did start to use angular2-jsonapi today. I will try to contribute to this project. Seems to me a good library to handle with the JsonAPI's integration.

**Comment by house-md** [comment]
@hpawe01 how does it look like with that pull request? is it released in latest version? thank you for info

**Comment by safo6m** [comment]
angular2-jsonapi@5 is compatible with Angular 5.
