### ISSUE TITLE
Error while trying to save Object

### ISSUE THREAD

**Issue by PaulMenheere** [ghidoz/angular2-jsonapi#15]
when calling the save() method on the Model. I get an JSON.parse EXCEPTION error.

after some debugging I found that the attributesMetadata variable filled in the JsonApiModel.prototype.save function returns an 'undefined' value.

this is the payload send to the api:
```
"data": {
    "type": "organisations",
    "id": "1",
    "attributes": {}
  }
```

**Comment by ghidoz** [comment]
Can you please post here your Organisation model and the code that you use to make the call?

**Comment by ghidoz** [comment]
Have you decorated each attribute with the `Attribute()` decorator?

**Comment by PaulMenheere** [comment]
No I haven't. Overlooked this in the implementation.
Thanks for the suggestion.

**Comment by ghidoz** [comment]
Maybe I'll add some warning if you don't implement the decorators correclty ;)

**Comment by PaulMenheere** [comment]
I think that would be for the betterment of the code...
☺️
Same with the check on relationships (other issue I reported)



On Sun, Sep 25, 2016 at 2:17 PM +0200, "Daniele Ghidoli" <notifications@github.com<mailto:notifications@github.com>> wrote:


Maybe I'll add some warning if you don't implement the decorators correclty ;)
