### ISSUE TITLE
extend  JsonApiModel when the class has extended another class 

### ISSUE THREAD

**Issue by GhEllie** [ghidoz/angular2-jsonapi#16]
Hi there,
As you now multi inheritance is not allowed in Javascript . So if we have a class which is extending an abstract class , we can not inherit from JsonApiModel anymore .

A sample is here :
export class Market extends ReferenceDate{
    id: string;
    name: string;
}

if I change the abstract class like this:
export abstract class ReferenceData extends JsonApiModel {
}

then I can not create any new instance of market in this way:
var market= new Market();

I will have syntax error because it needs datastore: JsonApiDatastore, data: any

**Comment by ghidoz** [comment]
The class models are intended to be created through the `createRecord` method:

`let market = this.datastore.createRecord(Market);`

or

`let market = this.datastore.createRecord(Market, {
    id: '1',
    name: 'test'
});`

**Comment by GhEllie** [comment]
It works for me .Thanks :)
