### ISSUE TITLE
Is there a way to clone a data model?

### ISSUE THREAD

**Issue by Liranius** [ghidoz/angular2-jsonapi#162]
For some reason I need to clone a model to avoid value being changed when processing the data. I wrote a method to deep clone the model. However, all attributes was getter/setter becomes premitive values. I also tried Object.getOwnPropertyDescriptors but it creates references to old model rather than clone it. I think it will be better if there is a clone method for the JsonApiModel.

**Comment by house-md** [comment]
@Liranius in our application we use lodash deepClone and its without problems. When I will have some free time I will try to create pull request with this function
