### ISSUE TITLE
Any way to dynamically change the baseURL

### ISSUE THREAD

**Issue by guy-roberts** [ghidoz/angular2-jsonapi#173]
Hi,
I've got a multi tenanted backend, and the client won't know which subdomain to use until the user choses it, so I need to set the baseURL on the fly.  

It looks like the DatastoreConfig can only be set when JsonApiDatastore is created. 

Can you suggest an approach ?

Thanks anyway.

**Comment by jacobbullock** [comment]
I was debugging a different issue today and I think I found a solution to this.  In your class that extends JsonApiDatastore and defines models you can access the baseUrl in there through 'this.datastoreConfig.baseUrl`

Example:

    @Injectable()
    @JsonApiDatastoreConfig(config)
    export class Datastore extends JsonApiDatastore {

      constructor(http: HttpClient) {
        super(http);
      }

      setBaseUrl(url: string): void {
        this.datastoreConfig.baseUrl = url;
      }
    }

**Comment by guy-roberts** [comment]
Perfect.   I had looked at the source and mistakenly thought I could not call setBaseUrl.

Thanks so much.
