### ISSUE TITLE
New Headers with authorization not working

### ISSUE THREAD

**Issue by arthurhamon** [ghidoz/angular2-jsonapi#176]
Hi,

Can you update the documentation to show an exemple of usage for custom headers in findall, findrecords etc request. 
Since you update to HttClient, you break the usage of custom Header.

Thanks

**Comment by hpawe01** [comment]
Hey @arthurhamon,

there is a testcase for this: https://github.com/ghidoz/angular2-jsonapi/blob/master/src/services/json-api-datastore.service.spec.ts#L119

And since the testcase doesn't fail it should still work.

Can you specify how it exactly fails (e.g. error message) and a example snippet?

**Comment by arthurhamon** [comment]
![capture](https://user-images.githubusercontent.com/1702391/40614741-5de9089e-6284-11e8-9cd9-d6e4399203fa.JPG)

And the code associated 

`const headers = new Headers({'Authorization': 'Basic ' + user.basic});`
`.findAll(
          User,
          {
            include: GET_USER_INCLUDES,
            filter: {
              'uid': {
                value: uid
              }
            }
          },
          headers,
          this._appInit.getApiUrl(DRUPALCONSTANT.user_endpoint)
        )`

**Comment by arthurhamon** [comment]
Problem solved !
Just remove the import of Header from @angular/http

Thanks for watching

**Comment by hpawe01** [comment]
That was, what I just wanted to suggest ;)
Cool that it worked.
