### ISSUE TITLE
Explanation for "level <= 2"

### ISSUE THREAD

**Issue by arthurhamon** [ghidoz/angular2-jsonapi#178]
Hi,

Can you tell me why on 'json-api.model.js' file, on 'getHasManyRelationship' function you have at line 157 this condition "if ( level <= 2 )" ?

Same, on 'getBelongsToRelationship' function at line 180  ( if ( level <= 2 ) ).

Why limit to 2 and not infinite ?

Thanks

**Comment by safo6m** [comment]
The fix is released in `v5.1.1-beta`,
