### ISSUE TITLE
How to fetch relationships?

### ISSUE THREAD

**Issue by kamil-zielinski** [ghidoz/angular2-jsonapi#189]
Is it possible to perform request like this?
`GET /articles/1/relationships/comments HTTP/1.1`
http://jsonapi.org/format/#fetching-relationships

**Comment by kamil-zielinski** [comment]
Ok, I think I found one possibility. [4. parameter of `findAll`](https://github.com/ghidoz/angular2-jsonapi/blob/master/src/services/json-api-datastore.service.ts#L62) is `customUrl` and it can be used.

Is there any other possibility so that I don't have to provide host and api version again to build url?

**Comment by house-md** [comment]
Right now is only solution to create customUrl yourself as You mentioned, but I think about implementing this feature in near future to be able load these right from model with something like this:

```typescript
this.article.relationships(Comment);
```

**Comment by kamil-zielinski** [comment]
I think it would be useful.

**Comment by Tonio-lavanda** [comment]
Has this feature been implemented ?
