### ISSUE TITLE
Roadmap to v4.0.0

### ISSUE THREAD

**Issue by reva2** [ghidoz/angular2-jsonapi#19]
Hi @ghidoz,

Do you have a detailed roadmap for this project? 

I really like your idea about using decorators. It's very much like the Hibernate or Doctrine ORM. But currently this library missing several important features and couldn't be used in real products.

At work we started a long-term project that have JSON API backend and currently looking for library that allow us consume this backend in Angular 2 apps. I studied several existing libraries and found that your library most in line with our vision of how client-side should interact with JSON API backend.

I would like to help you improve this library and make it useful for real products.

**Comment by ghidoz** [comment]
Hi! Actually I don't have a detailed roadmap, since I'm working on it in spare time (unfortunately, at work we don't use JSON API, so I'm not using it in real products yet).

At the moment I'm adding some unit tests and then I plan to work on this [TODO list](https://github.com/ghidoz/angular2-jsonapi#todo).

I am following the documentation and the features of [Ember Data](https://guides.emberjs.com/v2.8.0/models/), so that the idea is to add all the functionalities it has.

I would really appreciate your help in improving the library, since I have not so much time for working on it (a little bit during the evening and in the weekends).

What do you think are the priorities to work on?

**Comment by bonejon** [comment]
@ghidoz we are going to be using jsonapi for our current project, and also plan on using this library for the client side functionality.

I would be happy to assist with development where I can.

**Comment by ghidoz** [comment]
Awesome guys! So we have a team! 👍 
I think we can decide together what functionalities are critical and who develops them. Maybe we can create an issue for each feature and discuss them. What do you think?

**Comment by bonejon** [comment]
Sounds good, I've got a couple of simple starters, I'll create a couple of issues for them. 

I already have a PR to remove the dependency on typings.

**Comment by reva2** [comment]
Hey guys,

> I am following the documentation and the features of Ember Data, so that the idea is to add all the functionalities it has.

We already have [js-data](http://www.js-data.io) with [JSON API adapter](https://github.com/BlairAllegroTech/js-data-jsonapi). So I'm not sure that it's good idea to completely follow Ember Data way. I don't want to use js-data because I want to have much more grained control over requests and data storage.

I think that we need to think about significant refactoring in core to prevent some issues in the future. I'll create issues for all ideas that I have in several next days. But in any case we need to start from writing tests for already existing code.

**Comment by ghidoz** [comment]
> So I'm not sure that it's good idea to completely follow Ember Data way.

I'm not completely following it. Just inspiring to the methods interface. But of course we can diverge from it as much as we like!

> I think that we need to think about significant refactoring in core to prevent some issues in the future. 

What do you think are the most critical issues right now? What would you refactor?

> I'll create issues for all ideas that I have in several next days.

Awesome, looking forward to it.

> But in any case we need to start from writing tests for already existing code.

I absolutely agree! I already started (3dd157c) and I'll keep doing it.

**Comment by ghidoz** [comment]
Guys, I like your ideas. I think we can start to think to a v4.0.0 where we can implement the changes you suggested: https://github.com/ghidoz/angular2-jsonapi/milestone/1

We should also discuss if moving all the logic from the models to the datastore, as suggested by @reva2 in [this comment](https://github.com/ghidoz/angular2-jsonapi/issues/28#issuecomment-253164587).

**Comment by HennerM** [comment]
Closed due to inactivity, feel free to reopen if this was done by mistake.
