### ISSUE TITLE
Missing dist folder in 6.0.1-beta

### ISSUE THREAD

**Issue by daanoz** [ghidoz/angular2-jsonapi#192]
Hi, 

It looks like both 6.0.0-beta & 6.0.1-beta are published without an actual `/dist` folder, but the package.json file is referring as main file to `/dist/index.js`. Is it possible that it gets published with the dist folder like all 5.\*.\* version were done?

Thanks,
Daanoz

**Comment by safo6m** [comment]
@daanoz fixed in v6.0.2-beta
The new angular compiler changed the build structure.
