### ISSUE TITLE
Records sometimes return with null in everything other than ID. 

### ISSUE THREAD

**Issue by peavers** [ghidoz/angular2-jsonapi#194]
findRecord seems to periodically return null values for everything other than the ID field. I can confirm that my backend is sending the data, however when inspecting it in the console I can see that everything is null. 

Using the latest version and calling the findRecord method as
```
    this.datastore.findRecord(Steak, id).subscribe((steak: Steak) => {
      console.log(steak);
    });
```
The steak object has null on every attribute but it's ID. Is there some strange caching behavior going on? 

Any insight to this?

**Comment by house-md** [comment]
Hello,
Could you please show response from server and your Steak model?
Which version of angular2-jsonapi are you using?

**Comment by peavers** [comment]
Sure thing, the backend response...
```json
{
    "data": {
        "type": "steaks",
        "id": "5bb154490cc4c8e578e78b37",
        "attributes": {
            "title": "test",
            "owner": "m00001",
            "version": "stable",
        },
        "relationships": {
            "builds": {
                "data": [
                    {
                        "type": "builds",
                        "id": "5bb163550cc4c8f1e3d2a765"
                    }
                ]
            }
        }
    }
}
```
And the model 
```js
@JsonApiModelConfig({
  type: 'steaks'
})
export class Steak extends JsonApiModel {

  @Attribute()
  title: string;

  @Attribute()
  owner: string;

  @Attribute()
  version: string;

  @HasMany()
  builds: Build[];
}
```

I think it has something to do with the relationship. If I save a new Build then try and retrieve the Steak object the behaviour occurs consistently. I will try and put together a working example today if I have time, unless you spot an obvious mistake in my side of things.
