### ISSUE TITLE
Add documentation about sent parameters

### ISSUE THREAD

**Issue by SnezanaDichevska** [ghidoz/angular2-jsonapi#195]
Please add  documentation how payload is sent on POST/PUT (the format)

**Comment by hpawe01** [comment]
As they follow the [JSON API spec](https://jsonapi.org/format/), you can read about the format [here for POST](https://jsonapi.org/format/#crud-creating) and [here for PATCH](https://jsonapi.org/format/#crud-updating) (they don't use PUT).
