### ISSUE TITLE
Custom HTTP headers

### ISSUE THREAD

**Issue by dbenninger** [ghidoz/angular2-jsonapi#2]
I am calling a JsonApi service that requires OAuth2 authentication. It would be cool, if we could set custom HTTP headers somehow... 

Btw.. nicely done!

**Comment by ghidoz** [comment]
Good point! Do you want to set them just once for every call, or different headers for each call?

**Comment by dbenninger** [comment]
Once for every call should be fine, as long as we can update them any time...

**Comment by thnico** [comment]
As far as headers are concerned, shall we add the JSON API media type (http://jsonapi.org/#mime-types) ?
Content-Type: application/vnd.api+json

**Comment by ghidoz** [comment]
I already add them by default to every call

**Comment by ghidoz** [comment]
Please check the new v1.1.0 and the documentation: https://github.com/ghidoz/angular2-jsonapi#custom-headers

@dbenninger does it fulfill your needs?

**Comment by dbenninger** [comment]
very nice! Thanks!
