### ISSUE TITLE
Support for Polymorphic Relations?

### ISSUE THREAD

**Issue by Wizofgoz** [ghidoz/angular2-jsonapi#201]
I was looking over the readme and didn't see anything regarding the handling of polymorphic relations. Are they supported by the library at the moment?

For example, in my API there are invoices that can be assigned to any one of 3 model types.

**Comment by hpawe01** [comment]
Did you tried something like
```typescript
@BelongsTo()
billable: BillableA | BillableB | BillableC
```

The client will send the correct relationship to the server, e.g.
```json
{
  "data": {
    "type": "invoices",
    "id": "12",
    "attributes": {},
    "relationships": {
      "billable": {
        "data": {
          "type": "billablesA",
          "id": "123"
        }
      }
    }
  }
}
```

Your server needs to be able handle this though.

**Comment by Wizofgoz** [comment]
Ok, I was wondering if that would work. I haven't implemented anything yet, I was just wondering if it was supported to compare this to other packages
