### ISSUE TITLE
How to handle to-one relationships in models?

### ISSUE THREAD

**Issue by WimWidgets** [ghidoz/angular2-jsonapi#204]
How do you handle _to-one_ relationships in a model? Handling _to-many_ relationships are straightforward like this:
```typescript
export class Foo extends JsonApiModel {
  @HasMany()
  bars: Bar[];
}

export class Bar extends JsonApiModel {
  @BelongsTo()
  foo: Foo;
}
```

But there doesn't seem to be an equivalent decorator for _to-one_ relationships like so:
```typescript
export class Foo extends JsonApiModel {
  @HasOne()
  bars: Bar;
}
```

Is the support for such an attribute on a roadmap or is there another solution? It would be weird if there's no support, because according to the JSON API documentation both _to-one_ and _to-many_ relationships are supported:

https://jsonapi.org/format/#document-resource-object-linkage
> - null for empty to-one relationships.
> - an empty array ([]) for empty to-many relationships.

**Comment by letsbelopez** [comment]
@WimWidgets have you been successful in updated the to-one relationship?

I opened up a new issue about it [here](https://github.com/ghidoz/angular2-jsonapi/issues/221#issue-442849980)
