### ISSUE TITLE
Replace underscore with lodash

### ISSUE THREAD

**Issue by bonejon** [ghidoz/angular2-jsonapi#21]
Angular 2 uses lodash internally and here we use underscore. This has the possibility for errors as both libraries try to define window._

I have trialled this change locally and it seems to work without issue.

**Comment by ghidoz** [comment]
Ok, so you can make a PR ;)

**Comment by bonejon** [comment]
PR: https://github.com/ghidoz/angular2-jsonapi/pull/24

**Comment by ghidoz** [comment]
Thanks! Merged (61450c8)
