### ISSUE TITLE
Relationship config key doesn't seem to get used when saving a model

### ISSUE THREAD

**Issue by WimWidgets** [ghidoz/angular2-jsonapi#210]
The relationship config property `key`, to convert property names, only seems to work for incoming data and not for outgoing data (saving). I haven't experienced this issue with the similar attribute config property `serializedName`.

For example converting between camel case and dasherized.
```typescript
@JsonApiModelConfig({type: 'endpoints/things'})
export class Thing extends JsonApiModel {

    @BelongsTo({key: 'foo-bar'})
    fooBar: FooBar;
}

@JsonApiModelConfig({type: 'endpoints/foo-bars'})
export class FooBar extends JsonApiModel { }
```
For every retrieved `Thing` the `fooBar` property is properly set by the `foo-bar` property coming from the API. Saving a new `Thing` with a set `fooBar` property sends this property as `fooBar` to the API instead of `foo-bar`.

Payload to the server
```json
{
  "data": {
    "relationships": {
      "fooBar": {
        "data": {
          "type": "endpoints/foo-bars",
          "id": "1"
        }
      }
    },
    "type": "endpoints/things",
    "attributes": {}
  }
}
```

Is this a bug or am I missing something?

**Comment by WimWidgets** [comment]
I guess the problem is in the following lines:

https://github.com/ghidoz/angular2-jsonapi/blob/a736c0f88804d00049514d23071bf43a31761716/src/services/json-api-datastore.service.ts#L226
https://github.com/ghidoz/angular2-jsonapi/blob/a736c0f88804d00049514d23071bf43a31761716/src/services/json-api-datastore.service.ts#L237

Where the `key` is the literal property name of the model, instead of the `key` from the relationship config.

**Comment by hpawe01** [comment]
It looks like a bug. For a possible solution you could have a look here:
https://github.com/ghidoz/angular2-jsonapi/blob/a736c0f88804d00049514d23071bf43a31761716/src/models/json-api.model.ts#L162

The `key` is mapped to `relationship`: 
https://github.com/ghidoz/angular2-jsonapi/blob/a736c0f88804d00049514d23071bf43a31761716/src/decorators/belongs-to.decorator.ts#L7

So, a possible solution could look like (untested): 
```typescript
  protected getRelationships(data: any): any {
    let relationships: any;
    const belongsToAttributes: any[] = Reflect.getMetadata('BelongsTo', data); // <---

    for (const key in data) {
      if (data.hasOwnProperty(key)) {
        if (data[key] instanceof JsonApiModel) {
          relationships = relationships || {};

          if (data[key].id) {
            const belongsToAttribute = belongsToAttributes.find((config) => config.propertyName === key); // <--
            const relationshipKey = (belongsToAttribute && belongsToAttribute.relationship) || key;
            relationships[relationshipKey] = {
              data: this.buildSingleRelationshipData(data[key])
            };
          }
...
```
