### ISSUE TITLE
Support mixed types in HasMany relationship

### ISSUE THREAD

**Issue by hpawe01** [ghidoz/angular2-jsonapi#215]
A `HasMany` relationship (e.g. `books: Book[]`) does not allow mixed types (e.g. `CrimeBook`, `NovelBook`), even if they extend the same expected `HasMany` type (`Book`).

**Problem**
In this line, the type of the first element in the relationship is checked against all other types.
https://github.com/ghidoz/angular2-jsonapi/blob/a736c0f88804d00049514d23071bf43a31761716/src/services/json-api-datastore.service.ts#L249

**Example**
I have
```typescript
@HasMany()
books: Book[];
```
and the models
```typescript
@JsonApiModelConfig({
  type: 'crimeBooks',
  modelEndpointUrl: 'books'
})
export class CrimeBook extends Book {...}

@JsonApiModelConfig({
  type: 'novelBooks',
  modelEndpointUrl: 'books'
})
export class NovelBook extends Book {...}
```

**Possible solution 1**
Collect `modelEndpointUrl` or `type` of all relationship items and check if there is only one unique. This way, even if the `type` of the items differ (`crimeBooks` or `novelBooks`), if the `modelEndpointUrl` is the same (`books`), all should be fine.

**Possible solution 2**
Check, if all relationship items are instances of the model, that the `HasMany` attribute expects (`Book`).

I will create a pull request for solution 1, but I am not sure if solution 2 would be more clean (Although only `type` and `modelEndpointUrl` are relevant, when talking to the server, and not the Typescript type of the `HasMany` attribute).

**Comment by hpawe01** [comment]
Regarding *solution 2*: To realize this, TypeScript needs to expose the array element type (see https://github.com/Microsoft/TypeScript/issues/7169, e.g. `Book` for `Book[]`), so that we can check, that all items are instances of this array element type.

**Comment by safo6m** [comment]
Correct, the solution 2 is technically the correct one, but for now we can go with the solution 1 due to its simplicity.

**Comment by hpawe01** [comment]
Closing because #216 was merged.
