### ISSUE TITLE
Null date get converted to epoch on save

### ISSUE THREAD

**Issue by robert-hirsch-po** [ghidoz/angular2-jsonapi#242]
When an attribute is type `Date`, setting the value to null and calling save converts null to the epoch.

My API can accept either dates or null. Is it possible to actually send null with this library?

**Comment by e-marfoeldi-carnect** [comment]
I have solved that with my custom `DateConverter`

`import { format, parse } from 'date-fns';
import { PropertyConverter } from 'angular2-jsonapi';

export class DateConverter implements PropertyConverter {
  mask(value: any) {
    if (value === null) {
      return null;
    }

    return parse(value);
  }

  unmask(value: any) {
    if (value === null) {
      return null;
    }

    return format(value, 'YYYY-MM-DDTHH:mm:ssZ');
  }
}
`

In model file, you will use:
`
@Attribute({ converter: new DateConverter() })
`
