### ISSUE TITLE
Error: "dataType is not a constructor" in basic setup (example provided)

### ISSUE THREAD

**Issue by omcandido** [ghidoz/angular2-jsonapi#258]
Hi, 

I am having trouble to get a simple implementation of this library to work. I have followed the usage instructions and taken a look at the test files, but I keep getting **`ERROR TypeError: dataType is not a constructor`** when I perform a `findAll` search that returns any results. 

To make sure this is not a problem with my backend serving the data I have tried a very simple setup using a json:api playground: _http://jsonapiplayground.reyesoft.com/v2_. This way the issue can also be reproduced by anyone. Here are my files:

**datastore.service.ts**:
```
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { JsonApiDatastoreConfig, JsonApiDatastore, DatastoreConfig } from 'angular2-jsonapi';
import { Author } from '../models/author.model';

const config: DatastoreConfig = {
  baseUrl: 'http://jsonapiplayground.reyesoft.com/v2',
  models: {
    authors: Author
  }
};


@Injectable({
  providedIn: 'root'
})
@JsonApiDatastoreConfig(config)
export class DatastoreService extends JsonApiDatastore {
  constructor(http: HttpClient) {
    super(http);
  }
}
```

**author.model.ts**:
```
/* tslint:disable:variable-name */
import { JsonApiModelConfig, JsonApiModel, Attribute } from 'angular2-jsonapi';

@JsonApiModelConfig({
    type: 'authors'
})
export class Author extends JsonApiModel {

    @Attribute()
    name: string;

    @Attribute()
    birthplace: string;

    @Attribute()
    date_of_birth: string;

    @Attribute()
    date_of_death: string;

}
```

**app.component.ts**:
```
import { Component } from '@angular/core';
import { DatastoreService } from './services/datastore.service';
import { Author } from './models/author.model';
import { JsonApiQueryData } from 'angular2-jsonapi';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  constructor(private datastore: DatastoreService) { }

  public get() {
    this.datastore.findAll(Author, {
      page: { size: 10, number: 1 },
      filter: {
        name: 'Jacquelyn Hilpert',
      },
    }).subscribe(
      (authors: JsonApiQueryData<Author>) => console.log(authors.getModels())
    );
  }

}
```

**app.component.html**:
`  <button (click)="get()">Get</button>`

When clicking the Get button I should see the Jacquelyn Hilpert author entry with ID=1, but I get the error mentioned above.
Interestinlgy enough, if I remove all `@Attribute()` decorators and I leave the model empty, it causes the request to succeed (showing only the entry's ID). So the problem must be in the way the library builds the objects from the models.

I would really appreciate it if someone could tell me what I am doing wrong or if you are able to get this super simple example to work. 

**I am using Angular: 8.2.14**.

**Comment by hpawe01** [comment]
Please have a look at the README: https://github.com/ghidoz/angular2-jsonapi#angular-cli-configuration-for-cli-81. You need to add the `emitDecoratorMetadata` compiler options to your `tsconfig.json`.

**Comment by omcandido** [comment]
Oh, I was following the [npm README](emitDecoratorMetadata) of this project and that part is not mentioned. I imagined both READMEs would be the same, being the same project version.

Anyway, thank you for pointing it out, I would not have seen it otherwise. I cannot try that right now, but if that solves the problem I will close the issue.

**Comment by omcandido** [comment]
That solved the issue.
