### ISSUE TITLE
Deleting records

### ISSUE THREAD

**Issue by ghidoz** [ghidoz/angular2-jsonapi#28]
Even if there is a PR for the delete record feature (#20), actually, I would prefer having the `deleteRecord` on the model and not on the Datastore. Moreover, I would like to soft delete the record and then destroy it only when saving. Something like this:

```
this.datastore.findRecord(Post, '1').subscribe(
    (post: Post) => {
        post.deleteRecord();
        post.isDeleted; // true
        post.save(); // => DELETE /posts/1
    }
);
```
While for immediately deleting the method, I would like to use:
```
this.datastore.findRecord(Post, '2').subscribe(
    (post: Post) => {
        post.destroyRecord(); // => DELETE /posts/2
    }
);
```

The only tricky thing is handling the `rollbackAttributes()` method on a deleted record, before saving it.

Like the rest of the interface, this is inspired by [EmberData](https://guides.emberjs.com/v2.8.0/models/creating-updating-and-deleting-records/#toc_deleting-records).

Do you like this approach or do you prefer having the `deleteRecord` on the Datastore?

**Comment by wivern-co-uk** [comment]
I think it’s additional functionality which makes it obligatory to have an instance of model. Potentially it could lead to compulsion retrieving of significant amount of data in order to send delete request. It will make library less flexible. Soft delete is a nice feature, but I think it leads out of scope functionalities of "lightweight Angular 2 adapter for JSON API"

As for me PR #20 is very straightforward and it's what I like.

**Comment by reva2** [comment]
I prefer approach to have ```deleteRecord``` on the ```JsonApiDataStore```. 

In general, I think it will be better if we will use POJO augmented with decorators for data models. I.e. all methods that change data  in underlying storage (currently, ```save()```) should be moved from ```JsonApiModel``` to ```JsonApiDataStore```. 

Typical interaction with data storage can look like:
```typescript
// create record
let author = new AuthorModel();
storage.saveRecord(author);

// updating record
storage.findRecord(BookModel, '1').subscribe(
  (book) => {
    book.title = "New title";
    storage.saveRecord(book);
  }
);

// deleting record
storage.findRecord(BookModel, '1').subscribe(
  (book) => storage.deleteRecord(book);
);
```

This approach have following advantages:
- data models can be plain old javascript objects without dependency on ```JsonApiDataStorage```.  It can be easily created and tested.
- in the future we can easily support multiple operations in the single request (json-api/json-api#795). Something like:
```typescript
storage.beginTransaction();

/* posts: BlogPostModel[] */
posts.forEach((post) => {
  post.published = true;
  storage.saveRecord(post);  // request will be delayed because of transaction
});

storage.commit(); // update all posts in underlying storage using single request
```

**Comment by ghidoz** [comment]
Ok, guys. PR #20 merged and crafted a new version!

@reva2 Maybe you can open a new issue when we can discuss about moving logic from model to datastore, copying your last comment.

**Comment by reva2** [comment]
Done (see #34). I think you can close this issue.
