### ISSUE TITLE
Not working with angular-cli

### ISSUE THREAD

**Issue by caiges** [ghidoz/angular2-jsonapi#3]
Using the latest angular-cli, after following your instructions I get the following errors:

`zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/reflect-metadata`

It appears that systemjs is trying to load these via an xhr and obviously failing. It would seem that your projects dependencies would also need to be included in the vendor folder and thus, part of `angular-cli-build.js` and `system-config.ts`. I'm fairly new to TS so maybe I'm missing a crucial step here?

**Comment by jimbobhickville** [comment]
I'm working with @caiges on the same project.  I spent some time this morning trying to make this work. I added the following to `system-config.ts` to attempt to get it to load:

```
const map: any = {
  'angular2-jsonapi': 'vendor/angular2-jsonapi/dist',
  'underscore': 'vendor/underscore',
  'reflect-metadata': 'vendor/reflect-metadata'
};

const packages: any = {
  'angular2-jsonapi': {defaultExtension: 'js', main: 'index.js'},
  'underscore': {defaultExtension: 'js', main: 'underscore-min.js'},
  'reflect-metadata': {defaultExtension: 'js', main: 'Reflect.js'}
};
```

And `angular-cli-build.js` has:
```
    vendorNpmFiles: [
      'systemjs/dist/system-polyfills.js',
      'systemjs/dist/system.src.js',
      'zone.js/dist/**/*.+(js|js.map)',
      'es6-shim/es6-shim.js',
      'reflect-metadata/**/*.+(ts|js|js.map)',
      'rxjs/**/*.+(js|js.map)',
      '@angular/**/*.+(js|js.map)',
      'underscore/*.+(js|js.map)',
      'angular2-jsonapi/dist/**/*.+(ts|js|js.map)'
    ]
```

That got past the existing errors, but now it's failing on `zone.js:101 GET http://localhost:9090/crypto 404 (Not Found)`

I tried doing something similar to the above for the `crypto` module from npm, but then angular-cli fails to build on `Cannot find module 'package.json'`.  I also attempted to do it with the installed `hawk/crypto.js` but that just led to more 404 errors for other dependencies and I gave up at that point.  We're obviously doing something wrong here, but it's totally not obvious what.

**Comment by jimbobhickville** [comment]
Also, we're using the new `NgModule` syntax for bootstrapping, since `bootstrap` was deprecated:

```

import { PROVIDERS } from 'angular2-jsonapi';

@NgModule({
  imports: [
    BrowserModule,
    RouterModule.forRoot(routes)
  ],
  declarations: [
    AppComponent,
    PageNotFoundComponent
  ],
  providers: [ PROVIDERS ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

**Comment by ghidoz** [comment]
Here I am! You are right, I had the same problems at the beginning while developing it and I forgot to add these instructions in the README. Beside the `underscore` and `reflect-metadata`, you also have to add an empty reference to `crypto`. So, your `system-config.ts` becomes:

```
const map: any = {
  'angular2-jsonapi': 'vendor/angular2-jsonapi/dist',
  'underscore': 'vendor/underscore',
  'reflect-metadata': 'vendor/reflect-metadata',
  'crypto': '@empty'
};

const packages: any = {
  'angular2-jsonapi': {defaultExtension: 'js', main: 'index.js'},
  'underscore': {defaultExtension: 'js', main: 'underscore-min.js'},
  'reflect-metadata': {defaultExtension: 'js', main: 'Reflect.js'}
};
```

Let me know if it solves. Meanwhile I'll update the README.

**Comment by caiges** [comment]
I gave that a go but it seems like SystemJS doesn't walk the dependency tree. That solution will absolutely work btw, I'm just pointing out how fragile the SystemJS build for Angular apps is in general.

**Comment by ghidoz** [comment]
Yes, it's a problem with the `reflect-metadata` version used by Angular. Overwriting the `crypto` dependency, SystemJS just doesn't look for it anymore.

Btw they are moving to Webpack.

**Comment by caiges** [comment]
@ghidoz I saw that and tried it but it was a bit unstable for me atm. Using my own build simplified things and made all this come together. Great work on this package btw!

**Comment by ghidoz** [comment]
I understand. Well, I'll keep working on it ;)

**Comment by ghidoz** [comment]
Hey @caiges, if you want to give it again a try, let me know! Since the Angular CLI is not using SystemJS anymore, it should be better now!
