### ISSUE TITLE
Subscribe versus promise

### ISSUE THREAD

**Issue by ditproz** [ghidoz/angular2-jsonapi#37]
Where can I find information regarding how to handle subscribes.

Previously when using the http object, I can convert the observable into a promise and then pass that back to controller to manage the behavior of the app - for cases with success or failure.  

How do I accomplish the same with the subscribe() function?

Many thanks in advance...

**Comment by HennerM** [comment]
.subscribe() is method of `Observable`, in short, a Observable is a "multi-value promise". 

[http://stackoverflow.com/questions/37364973/angular-2-promise-vs-observable](url)

In the subscribe method you can pass callbacks for a `onNext`, `onCompleted` and `onError` events. Success is handled in onNext whileas failure is handled in onError.
[http://reactivex.io/documentation/operators/subscribe.html](url)

**Comment by ditproz** [comment]
Thanks - understood all is working now...

Thank you, at the moment, my observable is returned to my component to process the next, complete and error functions where appropriate.  Is that the right pattern or should these functions be processed within the service?
