### ISSUE TITLE
Dynamic configuration of urlBase

### ISSUE THREAD

**Issue by bonejon** [ghidoz/angular2-jsonapi#38]
During the development and test cycle of an application it's quite normal to have different environments for development and testing purposes. These environments could have different domain names, and or ports associated with the configuration.

Having the baseUrl parameter as part of the DataStore attributes makes this quite difficult to achieve. I've got a workaround for now, but it's not ideal. I have a think into a better solution, any suggestions would be appreciated.

**Comment by safo6m** [comment]
I've created a pull request regarding this issue: #61

**Comment by HennerM** [comment]
Waiting for update on pull request #61 otherwise I will do the change by myself.

**Comment by safo6m** [comment]
I'm working on customising the baseUrl and it will be finished somewhen next week.

**Comment by safo6m** [comment]
Done #99

**Comment by safo6m** [comment]
Merged to master.
