### ISSUE TITLE
Allow Http service to be injected in JsonApiDatastore

### ISSUE THREAD

**Issue by acramatte** [ghidoz/angular2-jsonapi#4]
I am using this angular2-jsonapi in the context of an Nativescript application. We use Nativescript-angular's [NS_HTTP_PROVIDERS](https://github.com/NativeScript/nativescript-angular/wiki/Http) instead of HTTP_PROVIDERS. They basically [extend the Http from Angular](https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/http/ns-http.ts#L57).

My issue is that the JsonApiDatastore completly ignores the provided Http from NS because it always [creates an injector from the HTTP_PROVIDERS](https://github.com/ghidoz/angular2-jsonapi/blob/master/src/services/json-api-datastore.service.ts#L15) so none of my calls to our json-api work.

I think that, ideally, the http service should be injected directly in the JsonApiDatastore because it is the reponsiability of the consumer of this library to provide it.

**Comment by ghidoz** [comment]
I absolutely agree. My first attempt was exactly what you are suggesting. This was the `JsonApiDatastore` constructor:

```constructor(private http: Http) { }```

and you should have to configure your datastore like this:

```
export class Datastore extends JsonApiDatastore {

  constructor(http: Http) {
    super(http);
  }
}
```

The problem was this error:

```Argument of type 'Http' is not assignable to parameter of type 'Http'.
Property '_backend' is protected but type 'Http' is not a class derived from 'Http'.````

and, after many researches, the only way to solve was creating an injector for the `HTTP_PROVIDERS`. If you can solve this, I'll be happy to inject the `Http` service directlty in `JsonApiDatastore`.

Thanks!

**Comment by acramatte** [comment]
> Argument of type 'Http' is not assignable to parameter of type 'Http'. Property '_backend' is protected but type 'Http' is not a class derived from 'Http'.`

That is weird. I have exactly the same changes you wrote in my fork but for me everything works fine.

Did you have different versions of angular between the app consuming this library and this library itself ?

**Comment by ghidoz** [comment]
Ok, I discovered the problem. I'm developing this library using npm link and there is some strange bug with dependencies. If I npm install it or if I just copy it in node_modules folder, it works.
I'll make your suggested change in the next release ;)

**Comment by acramatte** [comment]
Thanks @ghidoz 👍
