### ISSUE TITLE
@angular/http version dependency

### ISSUE THREAD

**Issue by bmayen** [ghidoz/angular2-jsonapi#46]
What work is involved with removing the strict dependency on the @angular/http version? We're inconveniently locked into v2.0.0 at the moment. 

Could the dependency be a more permissive peerDependency instead and allow the project to define the version?

**Comment by Eroxia** [comment]
What work is involved with removing the strict dependency on the @angular/http version? We're inconveniently locked into v2.0.0 at the moment.

Could the dependency be a more permissive peerDependency instead and allow the project to define the version?
