### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by supertino7** [ghidoz/angular2-jsonapi#49]
Hi there,

I'm facing a new problem with the object that Datastore returns me after making a findRecord(). 
I just added a service in my application to store some shared states and variables between my components. This [service](https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/app.service.ts) is inspired by the Angular2-Webpack starter. As you can see, it contains getter and setter definitions to make sure you never set directly a property and you always get a clone of the state object. 

```
    get state() {
        return this._state = this._clone(this._state);
    }
    set state(value) {
        throw new Error('You should not mutate the `.state` directly. Use set(prop, value) instead');
    }
    get(prop?: any) {
        const state = this.state;
        return state.hasOwnProperty(prop) ? state[prop] : state;
    }
    set(prop: string, value: any) {
        debugger
        // Mutate our state internally
        return this._state[prop] = value;
    }
    private _clone(object: InternalStateType) {
        return JSON.parse(JSON.stringify( object ));
    }
```

Here's for example one usecase in a component : 

```
constructor(private route: ActivatedRoute, 
            public appState: AppState, 
            private datastore: Datastore){ }

ngOnInit(){
        // Save current folder ID to the AppState service
        let folderId = this.route.snapshot.params['id'];
        this.appState.set('folderId', folderId);
        console.log(this.appState.get('folderId')); // Works fine.

        // Get current folder if needed
        if (!this.folder && !this.appState.get('folder')){
            this.datastore.findRecord(Folder, folderId)
                          .subscribe(
                              (folder: Folder) => {
                                  this.appState.set('folder', folder);
                                  console.log(this.appState.get('folder')) // Breaks here...
                              }
                          )
        }
    }
```

I have this output : 
`Uncaught TypeError: Converting circular structure to JSON(…)` 
anywhere I'll call `this.appState.get('folder')`
I guess it's because all the properties added to my folder object, like _datastore node or in the constructor, the object can't be passed into the `return JSON.parse(JSON.stringify( object ));` function.

What worry me is as for now I only use this basic state manager, but I'd like to implement something more substancial like ng2-redux, and I will likely encounter the same problem...

Any solution or workaround ? 
Thx for your help :)

**Comment by HennerM** [comment]
can you show us your Model definitions?
As in the error message said, `folder` contains circular references and you try to stringify this object. Eihter your class files have circular references or there is some circular reference in the `JsonApiModel` itself. If thats the case, that would be another argument to remove the dependencies in JsonApiModel ( #34 )
> private _clone(object: InternalStateType) {
        return JSON.parse(JSON.stringify( object ));
    }

**Comment by supertino7** [comment]
Hi 

Yes sure, my Model is pretty simple : 

```
import { JsonApiModelConfig, JsonApiModel, Attribute, HasMany, BelongsTo } from 'angular2-jsonapi';

@JsonApiModelConfig({
    type: 'folder'
})
export class Folder extends JsonApiModel {

    @Attribute()
    customerName: string;

    @Attribute()
    customerNumber: number;
    
    @Attribute()
    policyNumber: string;

    @Attribute()
    dateOfEvent: string;

    @Attribute()
    externalFolderId: string;
}
```

All the properties are not referenced in the model. But as far as I know, the backend returns me an object that's not deep with not known circular reference. So these seem to come from the JsonApiModel

**Comment by supertino7** [comment]
I tried to remove manually the _datastore property 

```
delete folder._datastore;
this.appState.set('folder', folder);
console.log(this.appState.get('folder'))
```

And it works. So it seems the circular references are within the _datastore node.
I don't know if I can proceed like that as a workaround, I have this warning : 
`Property '_datastore' is private and only accessible within class 'JsonApiModel'.`
and I don't know for the moment the use of the _datastore node

**Comment by bonejon** [comment]
A quick fix for this would be to implement a toJSON() method on your model.

You could also utilise a custom replacer to write a more generic version, see here https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#The_replacer_parameter for more details.

**Comment by HennerM** [comment]
Closing for now, efforts for remove the dependency on the datasore in the models is tracked in #34
