### ISSUE TITLE
Resource identifier id doesn't have to be a number

### ISSUE THREAD

**Issue by thnico** [ghidoz/angular2-jsonapi#5]
Angular2-jsonapi only supports numbers for resource identifier (id). Ex:

`findRecord(type: {
        new (data: any): JsonApiModel;
    }, id: number, params?: any, headers?: Headers): Observable<JsonApiModel>;`

 It's not compatible with Uuid for example.
The JSON API specification doesn't specify that identifiers have to be number. 

Therefore, can we allow the identifier to be a string as well ?

**Comment by ghidoz** [comment]
Thanks! Fixed with v1.2.1
