### ISSUE TITLE
How to get response headers?

### ISSUE THREAD

**Issue by webdesc** [ghidoz/angular2-jsonapi#50]
Hey.
The answer comes back clean model without headers. whether they can somehow get it?

**Comment by HennerM** [comment]
It's currently not possible.

**Comment by elliotlarson** [comment]
The API we're accessing gives us back a JSON web token in a header on every request.  It would be great if the `saveRecord` method returned an object that contained both the model object and the original http response so we could get at the returned headers.

**Comment by elliotlarson** [comment]
As a quick followup: we've ended up implementing a different approach that I think works better for our use case (handling JWT headers).  It involves extending the Http class, adding request response logic to it, and then having the Angular2 JSONAPI DatastoreService class use this instead.  

This approach is discussed in this blog entry: http://www.adonespitogo.com/articles/angular-2-extending-http-provider/
