### ISSUE TITLE
Update relationship attribute having a @BelongsTo() decorator

### ISSUE THREAD

**Issue by thnico** [ghidoz/angular2-jsonapi#51]
I have two models with OneToMany relationship:

```typescript
@JsonApiModelConfig({
    type: 'posts'
})
export class Post extends JsonApiModel {

    @Attribute()
    title: string;

    @HasMany()
    comments: Comment[];
}

@JsonApiModelConfig({
    type: 'comments'
})
export class Comment extends JsonApiModel {

    @Attribute()
    title: string;

    @BelongsTo()
    post: Post;
}
```

I'm getting one **Comment** and I update the **Post** it's belonging to: 

```typescript
this.datastore.findRecord(Comment, '1').subscribe(
      (comment: Comment) => {
        comment.post = anotherExistingPost;
        comment.save().subscribe();
      }
);
```

When I save, the **Post** my **Comment** is belonging to is not updated.

Actually my request that is being sent to the server doesn't contain anything to update:
```json
{
  "data": {
    "type": "comments",
    "id": "1",
    "attributes": {
      "id": "1"
    }
  }
}
```

For what I can see in the Library code, the save method is only taking in consideration the properties with **@Attribute()** decoration.
Unfortunately, my **post** property of **Comment** has a **@BelongsTo()** decoration.

```javascript
JsonApiModel.prototype.save = function (params, headers) {
    var attributesMetadata = Reflect.getMetadata('Attribute', this);
    return this._datastore.saveRecord(attributesMetadata, this, params, headers);
};
```

Then what should be done so that I can update the *Post* my *Comment* is belonging to ?

**Comment by bonejon** [comment]
I was looking at some code on Tuesday that may affect this.

Within json-api-datastore.ts - saveRecord at line ~ 47 there is this line of code:

    let relationships: any = !model.id ? this.getRelationships(model) : undefined;

From my understanding of the code this would mean relationships are only sent to the server when it is a new record. @ghidoz could you confirm this, and if there is any reason why please.

I am about to start a story where I will also need to perform updating of @BelongsTo relationships so there may be a PR soon.

**Comment by JoostVanAverbeke** [comment]
Good morning Daniele,

Your package angular2-jsonapi, looks very promising. I have setup a rails 5 api project as backend.
Now I have chosen angular2 as frontend. I would like to use your package to communicate with the rails backend. I have used angular-cli to create my initial project. I am using angular2 release 2.0.0.
But when I add the package "angular2-jsonapi": "3.3.0" to the dependencies in my package.json and add the JsonApiModule to my imports in the '@NgModule' of my app.module.ts file, I get the following error in the google browser:
 metadata_resolver.js:363Uncaught Error: Unexpected value '[object Object]' imported by the module 'AppModule'(…)
I must be doing something wrong. I am still an angular2 newbie.
Do you or does somebody else want to share a simple 'HelloWorld' like angular2 project using your angular2-jsonapi package. I would appreciate it a lot.
Many thanks in advance and sorry for using this comment for posting my question.
Joost

**Comment by ghidoz** [comment]
Here I am, sorry for the absence.

@bonejon I confirm that the relationship is sent only when creating a new record. In fact, in the TODO list in the README, the next step is "Updating or removing a relationship". I put off the implementation of the updating because it is quite tricky and I wanted to release the creation at least. If you want to implement it, a PR is welcome! ;)

@JoostVanAverbeke the new v3.4.0 should fix it. If you have any other problem, please comment this issue: #35

**Comment by HennerM** [comment]
Closed due to inactivity, feel free to reopen if this was done by mistake.
