### ISSUE TITLE
Single instance (question)

### ISSUE THREAD

**Issue by jasin755** [ghidoz/angular2-jsonapi#53]
Hi, I need to know how this library works with same data. For example: When I call 

````
this.datastore.findRecord(Post, '1').subscribe(
    (post: Post) => console.log(post)
);
````

twice. Will `post` be the same instance?

**Comment by ghidoz** [comment]
Hi, no it will make two different calls, with different instance.

If you want to retrieve the same instance, you should call `findRecord` the first time and `peekRecord` the second time.

In fact, when a record is retrieved by `findRecord` it will save it in cache and you can get it with the `peekRecord` method.
