### ISSUE TITLE
Unable to get pagination info when querying for multiple records

### ISSUE THREAD

**Issue by voronizer** [ghidoz/angular2-jsonapi#54]
So, I fetching list of posts as described in example:

```
this.datastore.query(Post, {
        page: { size: 10, number: 1}
    }).subscribe(
        (posts: Post[]) => console.log(posts)
    );
```

But there is no information in response about pagination links if server returns it.
See 
- http://jsonapi.org/format/upcoming/#fetching-pagination
- http://jsonapi.org/examples/#pagination

**Comment by mernen** [comment]
@HennerM Why was this closed? Is there any advance in this regard?

**Comment by mernen** [comment]
Looking at the source code, I see it’s possible to overwrite the `meta` constructor, thus allowing one to read any meta property they wish. Then, I guess it’s just a matter of documentation.
