### ISSUE TITLE
Cannot save HasMany relationship

### ISSUE THREAD

**Issue by jurgen-reconcept** [ghidoz/angular2-jsonapi#56]
How do I save a HasMany relationship?

It's clear from the readme that I can save a HasOne relationship just by setting the parameter with the object like

`{post: Post}`

but that doesn't seem to work for HasMany relationships when I use something like

`{comments: [Comment, Comment, Comment]}`

Is this not implemented yet? 

If not maybe I can help out (although I've never contributed to a github project before, so I may need some help).

**Comment by jurgen-reconcept** [comment]
I've forked the project and tried to get working on it, but when I try to use my local fork (no changes made) in the context of my project I suddenly get this error that I don't understand:

`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in ...`

Before, I used the original projects npm package, which worked just fine...

**Comment by HennerM** [comment]
Can you if you are still interested in this change try it with the most recent version?

**Comment by HennerM** [comment]
Closed due to inactivity, feel free to reopen.
