### ISSUE TITLE
make buildUrl in datastore.service protected instead of private

### ISSUE THREAD

**Issue by kimpixel** [ghidoz/angular2-jsonapi#62]
Hello 
First of all - good job with this lib.

I have an change request/question.

In our software we want the jsonapi resource Type in singular and the url-paths in plural.
Unfortunately in your lib is the method "buildUrl" in "json-api-datastore.service.ts" private and i am not allow to overwrite it.

My objective was to insert a new variable "path" in JsonApiModelConfig and use this instead in buildUrl.

**Comment by HennerM** [comment]
I think this is a reasonable request, although I need some time to think about possible better solutions.

**Comment by safo6m** [comment]
Hi @kimpixel, 

setting the base URL and building the API endpoints are changed a little bit and made more customizable. 
Check `DatastoreConfig` and `ModelConfig`, and raise the issue again if you are still not able to adapt the library to your needs.

Thanks
