### ISSUE TITLE
Support latest Angular, v4

### ISSUE THREAD

**Issue by klihelp** [ghidoz/angular2-jsonapi#68]

**Comment by blaur** [comment]
This one is also really high on my list. Any idea of when it would be done?

**Comment by HennerM** [comment]
It looks like the owner of the packag @ghidoz doesn't support the package anymore, would be better to fork it.

**Comment by HennerM** [comment]
I just got added as a collaborator on this project, this is definitely on my top-priority list. Will be able to start working on it next week.

**Comment by moneal** [comment]
Is this still a issue? I'm not having any problems with 4.3.1

**Comment by safo6m** [comment]
@moneal I believe that this is still the issue. Nevertheless, I upgraded dependencies to support Angular v4, #82
