### ISSUE TITLE
Can't add a query parameter to all requests

### ISSUE THREAD

**Issue by moneal** [ghidoz/angular2-jsonapi#71]
The API I'm working with requires a API key to get set as a query parameter. I can't find a way to configure this for all requests.

**Comment by HennerM** [comment]
It is true, there is no way to define global parameter. As I just started to revive this project the focus is first on bugfixing and maintenance instead of new features.

A way to accomplish the thing you want is to create a new method in your own `DataStore` class, something like this:
````
public queryWithParam<T extends JsonApiModel>(modelType: ModelType<T>, params?: any, headers?: Headers): Observable<T[]> {
    params["auth"] = "somevalue";
    return this.query(modelType, params, headers)
  }
