### ISSUE TITLE
Revive this repo

### ISSUE THREAD

**Issue by pascal08** [ghidoz/angular2-jsonapi#73]
Looking at this repository -- being the only serious JsonApi package for Angular -- I think it is a pitty that it seems like it is abandoned. I see a lot of forks so I can't be the only that has this feeling. 

I think we should stick our heads together and revive this package. Let me know what you think.

**Comment by HennerM** [comment]
As yesterday mentioned I will maintain this package from now on.
I will probably start resolving tickets and accepting PRs next week, I guess this shouldn't cause that much trouble since we already waited quite a long time now on updates.

**Comment by joaogarin** [comment]
This is great news! We are working on a decoupled CMS Solution called ["Contenta CMS"](https://twitter.com/contentacms) which is based on Drupal and works with jsonapi. We are developing several frontend demo projects for it two of them using angular and we are using this library as the CMS is now using jsonapi. If you would like to join the [slack channel](https://drupal.slack.com/messages/C5A70F7D1) and we would love to throw ideas and contribute to the repo in any way we can also, thanks for the great package and the hard work ;)

**Comment by joaogarin** [comment]
Also cool to see you are around Vienna;) maybe you want to present this library some time in the vienna Angular meetup! let me know if you are interested in that (connected via linkedin) I can set you up with the organizers. This is a great library! =) really glad to see this effort
