### ISSUE TITLE
Mocking models

### ISSUE THREAD

**Issue by joaogarin** [ghidoz/angular2-jsonapi#79]
Hello,

Is there any information about how to properly mock models for unit testing? Currently it seems there is a heavy amount of wiring needed if you have lets say an @input() which consits of 2 specific models..Creating those models requires to setup the datastore etc..

Is there a way to do this properly without needing to do this wiring that is in most cases unnecessary since the point is to test the component?

Best regards
Joao Garin

**Comment by joaogarin** [comment]
I noticed by looking at https://github.com/ghidoz/angular2-jsonapi/blob/master/src/models/json-api.model.spec.ts#L39 that you can do like : 

```javascript
const DATA = {
    id: '1',
    attributes: {
        name: 'Daniele',
        surname: 'Ghidoli',
        date_of_birth: '1987-05-25'
    }
};
let author: Author = new Author(datastore, DATA);
```

but still it expects a store

**Comment by HennerM** [comment]
That's something I want to address as part of #34 . But unfortunately this requires a big refactoring and a breaking change.

**Comment by joaogarin** [comment]
Thanks for the info. I am trying to setup some unit tests and was trying to pass null as the datastore. apparently that works for me locally to be able to run the test but doesnt on travis.

But good to know its on the roadmap ;) Looking forward.

Thanks for the help!

**Comment by HennerM** [comment]
Closing in favor of #34
