### ISSUE TITLE
Update github readme

### ISSUE THREAD

**Issue by RicardoNeves** [ghidoz/angular2-jsonapi#85]
I noticed that you're suggesting to use the deprecated `.query()` instead of `.findAll()`.

Keep on the good work.

**Comment by HennerM** [comment]
Hey,
thanks for the reminder, I have this on my list and will do this when I am back from vacation. However I would also appreciate pull requests.

Thanks, 
Markus

**Comment by RicardoNeves** [comment]
I'll try to do it during the week, and maybe have a look on some other issues. ;)

**Comment by HennerM** [comment]
Awesome, thanks a lot :)

**Comment by RicardoNeves** [comment]
Please have a look at #97  .
