### ISSUE TITLE
How to handle `dasherized` / `kebab-cased` attributes?

### ISSUE THREAD

**Issue by hpawe01** [ghidoz/angular2-jsonapi#86]
On server side I use the [JSON-API Framework Lux](https://github.com/postlight/lux). This delivers all attributes **dasherized**, e.g. `first-name`, independent of the case type internally used.
This is also [recommended by JSON API](http://jsonapi.org/recommendations/#naming):

> Member names SHOULD contain only the characters “a-z” (U+0061 to U+007A), “0-9” (U+0030 to U+0039), and the hyphen minus (U+002D HYPHEN-MINUS, “-“) as separator between multiple words.

How do I define my model in _Angular 2 JSON API_?
The following solution is obviously not working:
```
// from models/user.ts
@Attribute
first-name: string
```

But when I use the **camelCase** type:
```
// from models/user.ts
@Attribute
firstName: string
```
then the attribute is not recognised:
```
// from console.log():
first-name: "Foobar"
firstName: undefined
```
The same happens when I use the **snake_case** type (`first_name`).

I there a possibility to specify the casing, that should be used by  _Angular 2 JSON API_, both for GETting resources and POSTing/PATCHing resources?

Or is this a bug, and it should work out-of-the-box with the camelCase (`firstName`) or snake_case  (`first_name`) variant?

**Comment by HennerM** [comment]
Hey, 

I am not sure if this use-case is something that is needed a lot. I think the most flexible solution would be to allow a optional name attribute on the `@Attribute` decorator. This would allow to specify the serialized property name explicitly and can be backwards compatible. What do you think of this solution?

**Comment by ghidoz** [comment]
Hi! In theory, it should already be set in order to use do it:

`@Attribute('first-name')`

Please, try and let me know.

**Comment by hpawe01** [comment]
Hello,

thanks for your answers. The proposed solution from @HennerM would be indeed very flexibel, but @ghidoz, this is not working at the moment. I tried it and it had no effect. Also in the source code I could not find any indication for such an _attribute mapping_ (I looked at `src/services/json-api-datastore.service.ts`).

I will see, if I can make a pull request, but I am not at all experienced with this.

**Comment by HennerM** [comment]
I agree, there is no hint for this functionality in the codebase. Just working on a fix now.

**Comment by ricardo-neves-kununu** [comment]
@HennerM it would be nice to have this on the README file.

**Comment by HennerM** [comment]
It is not yet released in master, I will add the information before the change gets merged.
