### ISSUE TITLE
Patch method in service

### ISSUE THREAD

**Issue by floh1111** [ghidoz/angular2-jsonapi#9]
Hi,

do you plan to add a "patch" or a generic "save" method to the jsonapi-data-store.service?

Best whishes

**Comment by ghidoz** [comment]
Hi, yes I'm working on it!
Actually, I'm adding the save method directly to the model. See the [persistence branch](https://github.com/ghidoz/angular2-jsonapi/tree/persitence) and let me know what do you think.

I just need to fix some problems with the tracking of dirty attributes, before merging.

**Comment by ghidoz** [comment]
Here it is! Please check the new [v3.0.0](https://github.com/ghidoz/angular2-jsonapi/tree/v3.0.0) with many new features! Feel free to open new issues if you find any bugs.
Thanks!

**Comment by floh1111** [comment]
Nice! Tank you :)
