### ISSUE TITLE
Move away from Http and use Httpclient

### ISSUE THREAD

**Issue by wesselvdv** [ghidoz/angular2-jsonapi#95]
Move away from Http and use Httpclient. Allows us to use the Interceptor mechanic.

**Comment by agustinvinao** [comment]
I've created a pull request with a HttpClient implementation. https://github.com/ghidoz/angular2-jsonapi/pull/96

**Comment by hpawe01** [comment]
There was the switch to 4.0 a few days ago but this wasn't part of it. @agustinvinao are you planning to make a new pull request with only the HttpClient-Changes as suggested in the #96?

And does this mean, this will not be added until 5.0?

**Comment by KariiO** [comment]
Any news on that?
